//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.1
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSS.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://football.ua/rss2.ashx")]
        public string CURRENT_URL {
            get {
                return ((string)(this["CURRENT_URL"]));
            }
            set {
                this["CURRENT_URL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IS_PROXY {
            get {
                return ((bool)(this["IS_PROXY"]));
            }
            set {
                this["IS_PROXY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.1.4")]
        public string PROXY_IP {
            get {
                return ((string)(this["PROXY_IP"]));
            }
            set {
                this["PROXY_IP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3128")]
        public int PROXY_PORT {
            get {
                return ((int)(this["PROXY_PORT"]));
            }
            set {
                this["PROXY_PORT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IS_AUTHENTICATION {
            get {
                return ((bool)(this["IS_AUTHENTICATION"]));
            }
            set {
                this["IS_AUTHENTICATION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("boss")]
        public string PROXY_USER {
            get {
                return ((string)(this["PROXY_USER"]));
            }
            set {
                this["PROXY_USER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("393735ws")]
        public string PROXY_PASSWORD {
            get {
                return ((string)(this["PROXY_PASSWORD"]));
            }
            set {
                this["PROXY_PASSWORD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>http://football.ua/rss2.ashx</string>
  <string>http://ru.uefa.com/rssfeed/news/rss.xml</string>
  <string>https://www.championat.com/rss/news/football</string>
  <string>http://k.img.com.ua/rss/ru/all_news2.0.xml</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection URL_LIST {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["URL_LIST"]));
            }
            set {
                this["URL_LIST"] = value;
            }
        }
    }
}
